language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: bWtyFLviXA+mFtp8+UKYD7OwVGYRoenb1PeoUPz5Zm4iyEN+ClDjCB+7xpKVRMTWzxbUn4QQc8YoMpDtAMEZWpYZrT0YFvHJvZhewO96tJceAgQZqdx96HBsy8sexyV40ODXqxy1zaU6Y+Wk8Pf+dJVJlzww9wxLTOgLGJdWUpGFDnX4fl8pNKwCiyrmaFyXnzhZ3iUMuJGhphovzuRFEYFF27qlUEMysYBe/5pZkPdxbNZ7Cm4Gntduf9BAmdMMRn+jmEL5aJvDD1krBXPsFqRpjJCnhzTvu0SJyG3C63QPax9uZlAd14uloPYuH3xux115xwygx+wBdlN+Ob4HZyn5fKwvWFa7ROdxRUWMlj+D+ygSBCEjntIc1EGX9bd6ADgAACAQu81TYaJVnghBTS84aTacdrvlvOo5WukLUEhVs9wOD6BAL+VEfsMw9pHpwW5CcZCS5NhsT7xFSXuF7et/OuzSTPCs+CE8Z9Iu/jAPpn4efKeXgsXFEiDF/voHrdSsF4JkGqTsUHmcbsCwWVnYEwodKtggm93PsN27HYwC1qvda8kDs8TXG6sverjT+MhGp1yrxsuQr53qBo3IEPLapPZGXLgGtvm3aOz2JAXhhwUgWY+BrjwQPAH1wYqLgmpgdqhonpTHhrTvmQ6+6c5EPsvp2dGwbAc1jFK5pms=
    on:
      branch: master
      tags: true